service: employee-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DB_HOST: ${env:DB_HOST, 'localhost'}
    DB_NAME: ${env:DB_NAME, 'hrm_db'}
    DB_USER: ${env:DB_USER, 'hrm_user'}
    DB_PASSWORD: ${env:DB_PASSWORD, 'hrm_password'}

plugins:
  - serverless-offline

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /employees/{proxy+}
          method: any
          cors: true
      - http:
          path: /employees
          method: any
          cors: true
